name: node-build-and-deploy

on:
  # Trigger the workflow on a push to the main branch.
  push:
    branches: main

  # Allows you to run this workflow manually (for any branch) from the Actions tab.
  workflow_dispatch:

env:
  # 👇 Set the artifact name that will be used by the build and deployments, so it is now only defined in one place.
  artifactName: buildArtifact

jobs:
  set-version:
    runs-on: ubuntu-latest  
    outputs:
      version: ${{ steps.package-version.outputs.current-version }} 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    # - name: Get version from package.json
    #   id: set_package_version
    #   run: |
    #     version=$(jq -r '.version' package.json)
    #     echo "package_version=$version" >> "$GITHUB_ENV"
    # - name: Set build number
    #   id: set_build_number
    #   run: echo "build_number=${{ github.run_number }}" >> $GITHUB_ENV
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@v1.3.1
    - name: set-env
      run: echo "current-version=${{ steps.package-version.outputs.current-version }}" >> $GITHUB_ENV
  # 👇 Call the build workflow to create the artifacts to deploy, and provide the artifact name.
  build-and-test:
    needs: set-version
    uses: ./.github/workflows/node-build-template.yml
    with:
      artifactName: buildArtifact-${{ needs.set-version.outputs.version}}-${{ github.run_id }}
    secrets: inherit # Pass secrets to the build workflow, if necessary.

  deploy-to-dev:
    # Only run this deploy job after the build-and-test job completes successfully.
    needs: [set-version, build-and-test]
    # 👇 Call the deploy template with the proper environment name to deploy the artifacts.
    uses: ./.github/workflows/node-deploy-template.yml
    with:
      artifactName: buildArtifact-${{ needs.set-version.outputs.version}}-${{ github.run_id }}
      environmentName: dev
    secrets: inherit # Pass repository secrets to the deployment workflow.

  deploy-to-test:
    # Only run this deploy job after the build-and-test job completes successfully.
    needs: [set-version, deploy-to-dev]
    # 👇 Call the deploy template with the proper environment name to deploy the artifacts.
    uses: ./.github/workflows/node-deploy-template.yml
    with:
      artifactName: buildArtifact-${{ needs.set-version.outputs.version}}-${{ github.run_id }}
      environmentName: test
    secrets: inherit # Pass repository secrets to the deployment workflow.

  deploy-to-production:
    # Only run this deploy job after the deploy-to-staging job completes successfully.
    needs: [set-version, deploy-to-test]
    # 👇 Call the deploy template with the proper environment name to deploy the artifacts.
    uses: ./.github/workflows/node-deploy-template.yml
    with:
      artifactName: buildArtifact-${{ needs.set-version.outputs.version}}-${{ github.run_id }}
      environmentName: production
    secrets: inherit # Pass repository secrets to the deployment workflow.